// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0BbF1JvO4gHiF6BehaBmGUFGlWocyEi4',
    appId: '1:85543479471:web:0b157553cc8f992d1d0c5a',
    messagingSenderId: '85543479471',
    projectId: 'dict-88f0a',
    authDomain: 'dict-88f0a.firebaseapp.com',
    databaseURL: 'https://dict-88f0a-default-rtdb.firebaseio.com',
    storageBucket: 'dict-88f0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYwaZKfx4_u2oCPaoJeCLPIYXK-qm6ZWU',
    appId: '1:85543479471:android:2c992cb0f39f84ea1d0c5a',
    messagingSenderId: '85543479471',
    projectId: 'dict-88f0a',
    databaseURL: 'https://dict-88f0a-default-rtdb.firebaseio.com',
    storageBucket: 'dict-88f0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCizO8y6Nu7l7i9m2wsrfRBPlfodfnWGzA',
    appId: '1:85543479471:ios:8ecd10beda9b7bac1d0c5a',
    messagingSenderId: '85543479471',
    projectId: 'dict-88f0a',
    databaseURL: 'https://dict-88f0a-default-rtdb.firebaseio.com',
    storageBucket: 'dict-88f0a.appspot.com',
    iosClientId: '85543479471-uio4nk80nk6bjcisa005emmrnuvf6vh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.webrtcFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCizO8y6Nu7l7i9m2wsrfRBPlfodfnWGzA',
    appId: '1:85543479471:ios:7e43a4cba1ebf7b21d0c5a',
    messagingSenderId: '85543479471',
    projectId: 'dict-88f0a',
    databaseURL: 'https://dict-88f0a-default-rtdb.firebaseio.com',
    storageBucket: 'dict-88f0a.appspot.com',
    iosClientId: '85543479471-c2665lkp9maqkm0hgig4clvc6ueuj1pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0BbF1JvO4gHiF6BehaBmGUFGlWocyEi4',
    appId: '1:85543479471:web:45c44cca1ee56fb31d0c5a',
    messagingSenderId: '85543479471',
    projectId: 'dict-88f0a',
    authDomain: 'dict-88f0a.firebaseapp.com',
    databaseURL: 'https://dict-88f0a-default-rtdb.firebaseio.com',
    storageBucket: 'dict-88f0a.appspot.com',
  );

}